### ISSUE TITLE
Speakers summary using two languages

### ISSUE THREAD

**Issue by IvanBila** [mozdevz/DevFest18#11]
#### Summary

I noticed that the [speakers](https://devfestmaputo.firebaseapp.com/speakers/) page has the description written in both English and Portuguese, it would be nice if only one language is used, preferably Portuguese since that's the languages "most attendees" are fluent in. 

Maybe this implies that the presentations are going to be held in 2 languages, if so please close the issue.

![screenshot from 2018-11-28 11-23-31](https://user-images.githubusercontent.com/13482373/49141784-143ea700-f300-11e8-9e3e-e4fbc185f5b4.png)

**Comment by thatfiredev** [comment]
Thanks for bringing this up @IvanBila . That's really something we should do.

> Maybe this implies that the presentations are going to be held in 2 languages, if so please close the issue.

Actually, each session has it's language specified on the top right corner:
![screenshot from 2018-11-28 13-22-37](https://user-images.githubusercontent.com/16766726/49148717-c2524d00-f310-11e8-992d-4249a5ca578e.png)
